version: '3.8'

services:
  bol_app:
    build:
      context: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./bol:/bol
    environment:
      - SECRET_KEY=justransomsecretkey
      - DEBUG=1
